layout_spectrum: 0.4491048841737211
typography_spectrum: 0.2881050284486264
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5881326443050057
  lightness: 0.8739716608542949
  saturation: 0.7039033290930092
  rhythmicContrast: 0.6151026566512883
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: blogtest
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Blogger
description: May the force be with you.
purpose: []
